---

- name: Create
  hosts: localhost
  gather_facts: false
  connection: local
  serial: 1
  tasks:
    - name: Generate SSH-Key
      community.crypto.openssh_keypair:
        type: ed25519
        path: /root/.ssh/molecule

    - name: Push SSH-Key
      hetzner.hcloud.ssh_key:
        name: "molecule-{{ planet }}"
        state: present
        public_key: "{{ lookup('file', '/root/.ssh/molecule.pub') }}"
        api_token: "{{ token }}"

    - name: Setup Servers
      hetzner.hcloud.server:
        name: "{{ item.name }}"
        state: present
        server_type: cx22
        image: "{{ item.image }}"
        location: nbg1
        ssh_keys:
          - "molecule-{{ planet }}"
        api_token: "{{ token }}"
      register: create_server
      loop: "{{ molecule_yml.platforms }}"

    - name: Generate molecule-ssh_config
      template:
        src: molecule-ssh_config.j2
        dest: molecule-ssh_config
      vars:
        hosts: "{{ create_server.results }}"

    - name: Pause
      pause:
        seconds: 30
