---

- name: Destroy
  hosts: localhost
  gather_facts: false
  connection: local
  serial: 1
  tasks:
    - name: Delete Servers
      hetzner.hcloud.server:
        name: "{{ item.name }}"
        state: absent
        api_token: "{{ token }}"
      loop: "{{ molecule_yml.platforms }}"

    - name: Remove SSH-Key
      hetzner.hcloud.ssh_key:
        name: "molecule-{{ planet }}"
        state: absent
        api_token: "{{ token }}"
