---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Service
      wait_for:
        port: 80
        timeout: 10
      register: verify_port
      failed_when: verify_port.failed
