---

- name: Install chrony on all servers
  hosts: all
  tasks:
    - name: Package
      apt:
        state: present
        name:
          - chrony

    - systemd:
         # ...

    - copy:
         # ...

    - restart:
         # ...
