---

- name: Install chrony on all servers
  hosts: all
  tasks:
    - name: Package
      apt:
        state: present
        name:
          - chrony

    - name: Service
      systemd:
         # ...

    - name: Configfile
      copy:
         # ...

    - name: Restart
      systemd:
         # ...
